#!/usr/bin/env node
/**
 * inject-metrics.mjs
 *
 * Run AFTER js-distributor-scripts (`npm run dist`). Does two things:
 *
 *   1. Runs `npm install` inside every generated server directory so the
 *      servers can actually start (cleanOutput:true in config wipes node_modules
 *      on every `npm run dist`).
 *
 *   2. Regenerates observability/prometheus/targets/app-instances.yml so
 *      Prometheus knows which host:port to scrape. The distributed servers
 *      expose /metrics on their own app port via express-prom-bundle.
 *
 * Usage:
 *   node scripts/inject-metrics.mjs
 *   node scripts/inject-metrics.mjs --config ./utils/config-valid.yml
 */

import { execSync }                              from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path                                      from 'node:path';
import { fileURLToPath }                         from 'node:url';
import yaml                                      from 'js-yaml';

const __dirname      = path.dirname(fileURLToPath(import.meta.url));
const DISTRIBUTOR_ROOT = path.resolve(__dirname, '..');
const REPO_ROOT        = path.resolve(DISTRIBUTOR_ROOT, '..');

// ── CLI args ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
function flag(name, fallback) {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? fallback : args[i + 1];
}

const configArg = flag('config', path.join(DISTRIBUTOR_ROOT, 'utils/config-valid.yml'));

// ── Helpers ───────────────────────────────────────────────────────────────────

function log(msg) { console.log(`[inject-metrics] ${msg}`); }

function loadConfig(configPath) {
  if (!existsSync(configPath)) throw new Error(`Config not found: ${configPath}`);
  return yaml.load(readFileSync(configPath, 'utf8'));
}

// ── npm install in generated servers ─────────────────────────────────────────
//
// cleanOutput:true in config-valid.yml deletes the entire output folder before
// regenerating — that wipes node_modules too. We reinstall them here so the
// servers are ready to `npm start`.

function installDeps(serverDir, id) {
  const pkgPath = path.join(serverDir, 'package.json');
  if (!existsSync(pkgPath)) {
    log(`  ${id}: no package.json, skipping`);
    return;
  }

  log(`  ${id}: npm install…`);
  try {
    execSync('npm install', {
      cwd:    serverDir,
      stdio:  'pipe',      // suppress npm output; errors still surface below
      timeout: 120_000,
    });
    log(`  ${id}: done`);
  } catch (err) {
    const msg = (err.stderr?.toString() || err.message || '').trim();
    log(`  ${id}: npm install failed — ${msg}`);
  }
}

// ── Regenerate app-instances.yml ─────────────────────────────────────────────
//
// Distributed servers expose /metrics on their own app port (express-prom-bundle).
// Monolith exposes /metrics on its main port (metricsRoutes.js).

const MONOLITH_PORT = 8080;

function regeneratePrometheusTargets(serverAssignments) {
  const targetsPath = path.join(
    REPO_ROOT, 'observability/prometheus/targets/app-instances.yml',
  );

  const lines = [
    '# AUTO-GENERATED by inject-metrics.mjs — do not edit by hand.',
    '# Re-run after adding/removing servers in the config.',
    '# Prometheus reloads this file every 30 s — no restart needed.',
    '',
    '# host.docker.internal resolves to the Windows/Mac host on Docker Desktop,',
    '# and to the host-gateway on Linux (extra_hosts in docker-compose.observability.yml).',
    '',
    '# ── Monolith ─────────────────────────────────────────────────────────────────',
    '- targets:',
    `    - host.docker.internal:${MONOLITH_PORT}`,
    '  labels:',
    '    app: dddsample',
    '    instance: monolith',
    '',
    '# ── Distributed servers ──────────────────────────────────────────────────────',
    '# /metrics is on the same port as the app (express-prom-bundle).',
    '- targets:',
    ...serverAssignments.map(
      ({ id, appPort }) => `    - host.docker.internal:${appPort}   # ${id}`,
    ),
    '  labels:',
    '    app: dddsample',
    '',
  ];

  mkdirSync(path.dirname(targetsPath), { recursive: true });
  writeFileSync(targetsPath, lines.join('\n'), 'utf8');
  log(`wrote ${path.relative(REPO_ROOT, targetsPath)}`);
}

// ── main ─────────────────────────────────────────────────────────────────────

function main() {
  const configPath = path.resolve(configArg);
  log(`Config: ${configPath}`);

  const config  = loadConfig(configPath);
  const servers = config.servers ?? [];

  if (servers.length === 0) {
    log('No servers defined — nothing to do.');
    return;
  }

  // Resolve the dist output folder from config (relative to the config file dir)
  const configDir    = path.dirname(configPath);
  const outputFolder = config.codeGenerationParameters?.outputFolder ?? '../dist/distributedValid';
  const distRoot     = path.resolve(configDir, outputFolder);

  const serverAssignments = servers.map((server) => ({
    id:      server.id,
    appPort: server.http?.port ?? MONOLITH_PORT,
  }));

  // Install dependencies in each generated server
  log('Installing dependencies…');
  for (const { id } of serverAssignments) {
    const serverDir = path.join(distRoot, id);
    if (!existsSync(serverDir)) {
      log(`  ${id}: directory not found — run npm run dist first`);
      continue;
    }
    installDeps(serverDir, id);
  }

  log('Server ports:');
  for (const { id, appPort } of serverAssignments) {
    log(`  ${id}  →  host.docker.internal:${appPort}/metrics`);
  }

  regeneratePrometheusTargets(serverAssignments);

  log('');
  log('Done. Start each distributed server:');
  for (const { id } of serverAssignments) {
    const serverDir = path.join(distRoot, id);
    log(`  cd ${path.relative(process.cwd(), serverDir)} && npm start`);
  }
  log('Or run:  npm run start:dist');
}

main();
