/**
 * load-test.js  —  k6 load test
 *
 * Reads load-test-config.json (generated by `npm run inject:metrics`) to
 * discover which endpoints to hit and with what parameters.  The mapping is
 * derived from config-valid.yml, so this script works for every extraction
 * plan without modification:
 *
 *   Plan 1 (monolith): all functions → localhost:8080
 *   Plan 2 (alpha+beta): createCargo → localhost:3002, rest → localhost:8080
 *   …
 *
 * Run:
 *   k6 run scripts/load-test.js
 *
 * Push metrics to Prometheus (start observability stack first):
 *   k6 run --out experimental-prometheus-rw scripts/load-test.js
 *   (set K6_PROMETHEUS_RW_SERVER_URL=http://localhost:9090/api/v1/write)
 */

import http    from 'k6/http';
import { check, sleep } from 'k6';
import { Trend, Counter, Rate } from 'k6/metrics';

// ── Load generated config ─────────────────────────────────────────────────────

const config = JSON.parse(open('./load-test-config.json'));

// ── k6 options from config ────────────────────────────────────────────────────

export const options = {
  ...(config.options ?? {}),
  tags: { plan: __ENV.PLAN ?? 'unknown' },   // tag all metrics with plan name
};

// ── Build weighted endpoint pool ──────────────────────────────────────────────
//
// Each endpoint appears (weight) times in the pool so random selection
// produces the right call distribution without extra logic.

const pool = [];
for (const ep of config.endpoints) {
  const w = ep.weight ?? 1;
  for (let i = 0; i < w; i++) pool.push(ep);
}

if (pool.length === 0) {
  throw new Error('load-test-config.json has no endpoints — run npm run inject:metrics first');
}

// ── Per-endpoint custom metrics ───────────────────────────────────────────────

const epDuration = {};
const epErrors   = {};

for (const ep of config.endpoints) {
  epDuration[ep.id] = new Trend(`endpoint_duration_${ep.id}`, true); // in ms
  epErrors[ep.id]   = new Rate(`endpoint_errors_${ep.id}`);
}

// ── Default function ──────────────────────────────────────────────────────────

export default function () {
  const ep  = pool[Math.floor(Math.random() * pool.length)];
  const url = ep.params ? `${ep.url}?${ep.params}` : ep.url;

  const res = http.request(ep.method ?? 'GET', url, null, {
    tags: {
      endpoint: ep.id,
      server:   ep.server,
      port:     String(ep.port),
    },
  });

  const ok = check(res, {
    'status < 500': (r) => r.status < 500,
  });

  epDuration[ep.id].add(res.timings.duration);
  epErrors[ep.id].add(!ok);

  // small random think-time between requests (0.5 – 1.5 s)
  sleep(0.5 + Math.random());
}
